version: '3.8'

networks:
  test-network:
    driver: bridge

services:

  mysql:
    image: mysql:8.0
    container_name: test-db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - test-network
    volumes:
      - db-data:/var/lib/mysql

  app-categories:
    build:
      context: ./backend/categories
      dockerfile: Dockerfile
    container_name: c-app-categories
    restart: always
    ports:
      - "8082:8082"
    environment:
      DB_HOST: test-db2
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - mysql
    networks:
      - test-network

  app-products:
    build:
      context: ./backend/products
      dockerfile: Dockerfile
    container_name: c-app-products
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: test-db2
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: test
    depends_on:
      - mysql
    networks:
      - test-network

  frontend:
    build:
      context: ./frontend/app-product-categories
      dockerfile: Dockerfile
    container_name: c-sistema
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - app-categories
      - app-products
    networks:
      - test-network

volumes:
  db-data:
